export const ADDNEW_SUMMARY = 'ADDNEW_SUMMARY';
export const GETALL_SUMMARY = 'GETALL_SUMMARY';
export const UPDATE_SUMMARY = 'UPDATE_SUMMARY';
export const DELETE_SUMMARY = 'DELETE_SUMMARY';

export const UPDATE_KEYWORD = 'UPDATE_KEYWORD';